### ISSUE TITLE
presentation nodes pruned

### ISSUE THREAD

**Issue by vladsrynty** [bseddon/XBRL#12]
I am trying to create report for the file (attached) using Estonian [taxonomy ](https://xbrl.eesti.ee/) for the year [2020](http://xbrl.eesti.ee/wp-content/uploads/2019/12/et-gaap_2020-4.zip).

```
$report = new \XBRL_Report('test.xbrl', 'test.xsd');
$report->excludeDefaultDimensionMembers();
$report->preparePresentation();
echo $report->toHtml();

```

[test.zip](https://github.com/bseddon/XBRL/files/5145874/test.zip)

Generated report is empty and logs complain about not finding roles

_[info] Unable to find role for et-gaap-cor_2020-01-01.xsd#et-gaap_CurrentAssets
[info] Unable to find role for et-gaap-cor_2020-01-01.xsd#et-gaap_NonCurrentAssets_ etc.

After debugging for a while I found out that reporting needs role paths (and hierarchy) to be set, but the arrays are empty.
They get pruned in XBRL class in the function pruneNodeHypercubes, because they are marked as dimensional.

Could you please have a look and give some suggestions how to fix this. 

Thank you!

**Comment by bseddon** [comment]
Hi Vladimir

I have been able to create reports for the test instance document but with a change.  Before describing my change, I'm going to state what I think you are trying to do and, if this is true, why you may be running into problems.

When I try to use test.xbrl there are a lot of taxonomy validation warnings.  It seems like you are trying to use test.xsd as an extension taxonomy.  test.xbrl links to test.xsd which in turn imports the 'et-gaap-cor_2020-01-01.xsd' schema and six of the role schemas.  It also references linkbases from the same six roles.  

I believe the problem is that oneof the roles you import do not define all the dimensions used.  One of the roles, 903000, defines a dimension used by role 843000,  If you look in linkbase 'def_NoteConsolidatedRelatedParties_role-843020.xml' on line 115 you will see that dimension 'AdditionalDimensionalAllocationByInterestRateBaseCurrenciesAndDueDateDurationDimension' is defined by by a 'targetRole' to used the definition in 903000.  Because test.xsd does not import 'role-903000.xsd' things start to go wrong.

If I change test.xbrl to link directly to 'et-gaap-cor_2020-01-01.xsd' instead of test.xsd then everything works and reports are generated.

When I then modified test.xsd to import 'role-903000.xsd' (and the two definition linkbases) then allowed test.xbrl to import test.xsd again, things started to working better.  Here is the modified test.xsd that works for me:  [test.zip](https://github.com/bseddon/XBRL/files/5146196/test.zip)

Here is a screenshot of one of the 6 reports created from the instance document you attached.  I chose to create the reports using Estonian labels.

![estonia](https://user-images.githubusercontent.com/1221824/91649274-09332080-ea6a-11ea-968a-25459d34e97c.png)

However, I did not use the XBRL_Report class to produce the reports,  These are every much deprecated now in favour of XBRL_DFR (Digital Financial Reporting).  There is an example of using this class in [./xbrl/examples/Case Study DK/generateHTML.php](https://github.com/bseddon/XBRL/blob/develop/examples/Case%20Study%20DK/generateHTML.php) and some information about it in the [Wiki](https://github.com/bseddon/XBRL/wiki/Digital-Financial-Reporting). 

XBRL_Report was created when I was learing about XBRL while XBRL_DFR has been created with the support of one of the founders of XBRL and this method of reporting is the only one that will be supported in the future.

**Comment by vladsrynty** [comment]
Extension taxonomy is given by Estonian Commercial Register, I'm only trying to read the instance document. I will report them that they should fix extension file. I wonder why they add it with every instance document. 

I will try to find time to create PR for estonian GAAP (et-gaap). the more the merrier I suppose.

Thank you for your help and the software! 👍

**Comment by bseddon** [comment]
Reading your comment this morning and looking at the issue again, I think the issue is with the processor because it should be able to pull the 'missing' role automatically.  I'll take another look today to see why the referenced role is not being accessed.

**Comment by vladsrynty** [comment]
I started investigating XBRL_DFR and if I use  'et-gaap-cor_2020-01-01.xsd' the facts are rendered, but for the roles (I did use the test file you fixed) the reports are empty.

```
$instance = \XBRL_Instance::FromInstanceDocument('test.xbrl', 'test.xsd');
$results = array();
$indent = 0;
$lang = null;
$instanceTaxonomy = $instance->getInstanceTaxonomy();
$instanceTaxonomy->generateAllDRSs();
$instance->validate();
$dfr = new \XBRL_DFR( $instanceTaxonomy );
$formulaSummaries = $dfr->validateFormulas( $results, $instance, $indent );

$role = 'http://xbrl.eesti.ee/role/et-gaap_2020-01-01/StatementOfFinancialPosition_role-201014';
$presentationNetworks = $dfr->validateDFR( $formulaSummaries );
print_r($presentationNetworks[$role]);
$results['renders'] = $dfr->renderPresentationNetworks( $presentationNetworks, $instance, $formulaSummaries, $observer, $lang, true );
print_r($renders[$role]);
```

presentationNeworks are listed, but paths and hierarchies are empty.

I cannot get the same result as you did. 

Output:

```
[info]     Files: test.xsd
[info]  et-gaap_2020-01-01/role-201000/role-201000.xsd
[info]  et-gaap_2020-01-01/role-301000/role-301000.xsd
[info]  et-gaap_2020-01-01/role-801000/role-801000.xsd
[info]  et-gaap_2020-01-01/role-839000/role-839000.xsd
[info]  et-gaap_2020-01-01/role-843000/role-843000.xsd
[info]  et-gaap_2020-01-01/role-702000/role-702000.xsd
[info]  et-gaap_2020-01-01/role-903000/role-903000.xsd
[info]  et-gaap-cor_2020-01-01.xsd
[warning] 0  There are no formulas
Array
(
    [type] => simple
    [href] => et-gaap_2020-01-01/role-201000/role-201000.xsd#StatementOfFinancialPosition_role-201014
    [roleUri] => http://xbrl.eesti.ee/role/et-gaap_2020-01-01/StatementOfFinancialPosition_role-201014
    [used] => 1
    [hierarchy] => Array
        (
        )

    [locators] => Array
        (
            [AssetsAbstract] => et-gaap-cor_2020-01-01.xsd#et-gaap_AssetsAbstract
            [Assets] => et-gaap-cor_2020-01-01.xsd#et-gaap_Assets
            [CurrentAssets] => et-gaap-cor_2020-01-01.xsd#et-gaap_CurrentAssets
            [NonCurrentAssets] => et-gaap-cor_2020-01-01.xsd#et-gaap_NonCurrentAssets
            [LiabilitiesAndEquityAbstract] => et-gaap-cor_2020-01-01.xsd#et-gaap_LiabilitiesAndEquityAbstract
            [LiabilitiesAbstract] => et-gaap-cor_2020-01-01.xsd#et-gaap_LiabilitiesAbstract
            [CurrentLiabilities] => et-gaap-cor_2020-01-01.xsd#et-gaap_CurrentLiabilities
            [ShortTermProvisions] => et-gaap-cor_2020-01-01.xsd#et-gaap_ShortTermProvisions
            [NonCurrentLiabilities] => et-gaap-cor_2020-01-01.xsd#et-gaap_NonCurrentLiabilities
            [LongTermProvisions] => et-gaap-cor_2020-01-01.xsd#et-gaap_LongTermProvisions
            [Liabilities] => et-gaap-cor_2020-01-01.xsd#et-gaap_Liabilities
            [EquityAbstract] => et-gaap-cor_2020-01-01.xsd#et-gaap_EquityAbstract
            [Equity] => et-gaap-cor_2020-01-01.xsd#et-gaap_Equity
            [IssuedCapital] => et-gaap-cor_2020-01-01.xsd#et-gaap_IssuedCapital
            [UnpaidCapital] => et-gaap-cor_2020-01-01.xsd#et-gaap_UnpaidCapital
            [LiabilitiesAndEquity] => et-gaap-cor_2020-01-01.xsd#et-gaap_LiabilitiesAndEquity
            [StatementOfFinancialPositionAbstract] => et-gaap-cor_2020-01-01.xsd#et-gaap_StatementOfFinancialPositionAbstract
            [StructureInstantAbstract] => et-gaap-cor_2020-01-01.xsd#et-gaap_StructureInstantAbstract
        )

    [paths] => Array
        (
        )

    [hypercubes] => Array
        (
        )

    [text] => [201014] Bilanss, osaühing, mikroettevõtja
    [axes] => Array
        (
        )

    [tables] => Array
        (
        )

    [lineitems] => Array
        (
        )

    [concepts] => Array
        (
        )

)
[info] http://xbrl.eesti.ee/role/et-gaap_2020-01-01/StatementOfFinancialPosition_role-201014
[info] http://xbrl.eesti.ee/role/et-gaap_2020-01-01/IncomeStatementScheme1_role-301011
[info] http://xbrl.eesti.ee/role/et-gaap_2020-01-01/NoteAccountingPolicies_role-801030
[info] http://xbrl.eesti.ee/role/et-gaap_2020-01-01/NoteLaborExpense_role-839030
[info] http://xbrl.eesti.ee/role/et-gaap_2020-01-01/NoteRelatedParties_role-843030
[info] http://xbrl.eesti.ee/role/et-gaap_2020-01-01/ProfitDistributionProposal_role-702015
Array
(
    [entities] => Array
        (
            [{http://xbrl.eesti.ee/estonian_commercial_register}14171886] => <div class='report-selection'>     <span class='report-selection-title'>Rendering sections:</span><input type='checkbox' name='report-selection' id='report-selection-component' data-class='component-table' checked /><label for='report-selection-component'>Component</label><input type='checkbox' name='report-selection' id='report-selection-structure' data-class='structure-table'  /><label for='report-selection-structure'>Structure</label><input type='checkbox' name='report-selection' id='report-selection-slicers' data-class='slicers-table' checked /><label for='report-selection-slicers'>Slicers</label><input type='checkbox' name='report-selection' id='report-selection-report' data-class='report-section' checked /><label for='report-selection-report'>Rendering</label><input type='checkbox' name='report-selection' id='report-selection-facts' data-class='facts-section'  /><label for='report-selection-facts'>Facts</label><input type='checkbox' name='report-selection' id='report-selection-Rules' data-class='business-rules-section'  /><label for='report-selection-rules'>Rules</label></div><div class='report-outer allow-constrained'>        <div class='model-structure constrained'>       <div class='component-table '>          <div class='ct-header'>Component: Network plus Table</div>              <div class='ct-body'>                   <div class='ct-body-header network'>Network</div>                       <div class='ct-body-content network'>                                <div>[201014] Bilanss, osaühing, mikroettevõtja</div>                           <div>http://xbrl.eesti.ee/role/et-gaap_2020-01-01/StatementOfFinancialPosition_role-201014</div>                        </div>                  <div class='ct-body-header hypercube'>Table</div>                    <div class='ct-body-content hypercube'>(Implied table)</div>            </div>  </div>  <div class='structure-table hide-section'>              <div>Label</div>                <div>Fact set type</div>                <div>Report Element Class</div>              <div>Period Type</div>          <div>Balance</div>              <div>Name</div> </div>  <div style='display: grid; grid-template-columns: 1fr; '>               <div style='display: grid; grid-template-columns: auto 1fr;'>There is no data to report         </div>  </div>  <div class='facts-section hide-section'>     </div>  <div class='business-rules-section hide-section' style='display: grid; grid-template-columns: auto 1fr; '>              <div>Business Rules</div><div></div>    </div>  </div>  <div></div></div>
        )

    [text] => [201014] Bilanss, osaühing, mikroettevõtja
    [hasReport] => 0
)
```

**Comment by bseddon** [comment]
OK.  I'll take a look at your example this evening.  In the meantime, did you initialize the DFR?

```php
XBRL_DFR::Initialize( $cacheLocation );
```

$cachelocation is some place you want to use to cache downloaded XML files.  You will then intialize the context with the same location.

```php
// Initialize the cache
$context = \XBRL_Global::getInstance();
if ( ! $context->useCache )
{
	$context->useCache = true;
	$context->cacheLocation = $cacheLocation;
	$context->initializeCache();
}
```

You will see these are the same initalizations as are used in [./xbrl/examples/Case Study DK/generateHTML.php](https://github.com/bseddon/XBRL/blob/develop/examples/Case%20Study%20DK/generateHTML.php) (lines 139 and 161).

This zip file contains the HTML output I see.  Expand it some place then review ./html/test/index-et.html When we have it working for you, this is what you should see.

[estonia_report.zip](https://github.com/bseddon/XBRL/files/5146916/estonia_report.zip)

**Comment by vladsrynty** [comment]
It did work with initialization, I have the reports.
Is it possible to prepare compiled version of main  'et-gaap-cor_2020-01-01.xsd' once, but compile extension xsd, that comes with the instance?

**Comment by bseddon** [comment]
There is a function XBRL::compileExtensionXSD().  It's purpose is to do as you suggest but its relatively untried.  The intention is to allow the large US-GAAP taxonomies to be compiled and used with corporation extension taxonomies.  However, I'm not so sure how effective it is.

In principle you can load a compiled 'core' taxonomy and then load another, such as test.xsd.  When the core taxonomy is imported by test.xsd the code will use the version already loaded.

The challenge for you is that the ET core taxonomy only loads concepts.  The core does not reference any linkbases so loading these will occur every time test.xsd is loaded.  Of course once test.xsd is compiled and saved then it can be loaded straight away.  

Of course this is not so useful if there is a one-to-one correspondence between schemas (.xsd) and instance documents (.xbrl).

**Comment by bseddon** [comment]
Earlier I made the comment that, perhaps, the XBRL processor should be able to find the additional linkbases.  However, having looked again today, I cannot see how those linkbases can be found automatically.  The [XBRL specification section 3.2](http://www.xbrl.org/Specification/XBRL-2.1/REC-2003-12-31/XBRL-2.1-REC-2003-12-31+corrected-errata-2013-02-20.html#_3.2) lists 6 method a processor can use to find a linkbase.  So far as I can tell, the required extra linkbase cannot be found using any of the methods.

So far as I am able to determine, the correct things to do is to add the extra <linkbaseRef> elements to test.xsd as you have done.

**Comment by vladsrynty** [comment]
Probably I misunderstand it, as xbrl learning curve is quite steep, but:

Method 4. referenced from a discovered linkbase document via a <roleRef> element. Every taxonomy schema that is referenced by an @xlink:href attribute on a <roleRef> element in a discovered linkbase MUST be discovered.

In the file def_NoteRelatedParties_role-843030.xml  on line 23:
<link:roleRef roleURI="http://xbrl.eesti.ee/role/et-gaap_2020-01-01/AdditionalDimensionalAllocationByInterestRateBaseCurrenciesAndDueDateDuration_role-903010" xlink:type="simple" xlink:href="../role-903000/role-903000.xsd#AdditionalDimensionalAllocationByInterestRateBaseCurrenciesAndDueDateDuration_role-903010"/>

no?

**Comment by bseddon** [comment]
You would think so but follow it through and bear in mind that there has to be an href to a *file* in order to access the file content. For example, the linkbase you mention (def_NoteRelatedParties_role-843030.xml) is loaded via the href attribute of a <linkbase> element in test.xsd.

In the example you gave, the processor will use the value of the href attribute of the <roleRef> element which references an id in the 'role-903000,xsd' file.  role-903000,xsd is loaded using the href value. However, the id is just a reference to a <roleType> element which identifies *how* a role is to be used but not *where* the role content is to be found.

If you search all the taxonomy files for the string 'def_AdditionalDimensionalAllocationByInterestRateBaseCurrenciesAndDueDateDuration_role-903010.xml' (because we know the content associated with role 'http://xbrl.eesti.ee/role/et-gaap_2020-01-01/AdditionalDimensionalAllocationByInterestRateBaseCurrenciesAndDueDateDuration_role-903010' is in this file) it does not exist. That is, there is no way for a processor to locate the role XBRL content.

I'll add some code later to show how the 'missing' linkbases can be added programmatically. In this way, user schemas like test.xsd do not need to be edited.

**Comment by vladsrynty** [comment]
I got the response from Commercial Register. Thank to your thorough explanation they are on it. They use Fujitsu validator which, as they say, does not complain (except for missing unitrefs). Arelle is also quiet. But I totally agree with you and can see the problem. I suppose using 3 different validators would yield a trustworthy result for taxonomy creators...

**Comment by bseddon** [comment]
If there are missing linkbase files (ones that do not get included somewhere) the problem for you is that is necessary to add elements to, say, test.xsd.  Here is a technique that allows you to load missing linkbases programmically.  This way no files need to be modified.

[XBRL-ET.zip](https://github.com/bseddon/XBRL/files/5168230/XBRL-ET.zip)

The attachment contains a zip file that implements a class called 'XBRL_ET' which extends the class 'XBRL'.  The class will load additional linkbases when the main (test.xsd) has been loaded. Here's how to use it.

```php
// Load the class AFTER the XBRL processor has been autoloaded
require_once('XBRL-ET.php');

// Get the schema file name (test.xsd) from the instance document
// $document contains the instance document path (for example /mypath/test.xbrl)
$schemaHRef = XBRL_ET::getInstanceTaxonomyHRef( $document );
// Create a fully qualified path from $schemaHRef  in case it is not fully qualified
$schemaHRef = XBRL::resolve_path( $document, $schemaHRef );
// Get the namespace for the schema
$namespace = XBRL_ET::getTaxonomyNamespace( $schemaHRef );

// Register namespace to class map entries so the XBRL_ET class will be used when test.xsd is loaded
XBRL::add_namespace_to_class_map_entries( array( $namespace ), "XBRL_ET" );

// Load the instance as usual for example...
$instance = XBRL_Instance::FromInstanceDocument( $document );
```

If validation is enabled many entries like this will be generated:

```
[warning] [dimension] The dimension cannot be located in the dimensions collection of the target role (Section 2.4.3 - target role: 'http://xbrl.eesti.ee/role/et-gaap_2018-01-01/AdditionalDimensionalAllocationByInterestRateBaseCurrenciesAndDueDateDuration_role-903010', dimension: 'et-gaap-cor_2018-01-01.xsd#et-gaap_AdditionalDimensionalAllocationByInterestRateBaseCurrenciesAndDueDateDurationDimension', location: resolvePrimaryItemHypercubeDRS, error: xbrldte:TargetRoleNotResolvedError)
```
Until the additional linkbases are loaded, the processor will be unable to find the target roles. However, once they have been loaded the references will be resolved correctly.
