### ISSUE TITLE
Getting a report from xsd

### ISSUE THREAD

**Issue by mehdimf20** [bseddon/XBRL#9]
hi
What steps do I need to take to report xsd?
thanks

**Comment by bseddon** [comment]
Please read the information available in this repository and in the [wiki](https://github.com/bseddon/XBRL/wiki).  I'm happy to answer questions about the code you have written but I am not writing your code for you.

**Comment by mehdimf20** [comment]
thanks for answer.
Some things don't make sense, I don't know how to get an instance document from xsd.
I read the whole wiki but didn't get it

**Comment by mehdimf20** [comment]
You have some examples in case studies, but nothing about building instances
